sudo: false
language: java
jdk:
- oraclejdk8
env:
  global:
  - BINTRAY_USERNAME=jonpasski
  - secure: HqXURvSSqjG/E3TfNqH5O5yPuXoCrItLbUHet3cYlmKrdRMxK7JytOt1i9QF/0XHUZMLf86hF1BeTGZ6bx7PcW4o3ivvIG1fClWcQAq0D8PThpsKWbaJ7YGyjDhuuSPunFQfmbfuwJHSP6GBKne6yAVK7n/bZDnSeVjMHmgQ9zdwnhXI/KJ6tElm/ItjW8DuceHj6AQOTdznxSM6z+3TGeqOwRWn6BMU0YypWDlfA5f1ZsGmRgDNynodp9wnZu2vKx0LKULxBycGrdonBp5WvwKesoWLS4rv9GECNv+8FKNTlthsOW5gBJiaTF5TURRZMbPtOs39dJfmHMJnw9R7q0XjYGGsP0uwJJ6nvyPfencV47WF47tX6fU/ll2lRlSIkjSI7I1vPCvsVE9obDmR6FT10gKH+ACVWaJ1eT0o/OSri6r4tveoRmpvRNRsPDsOV6OB/jNC5xn8QBtwfg1wo+f/RTT2G7E+07VNLXeDdrLy/sikur1Z6LvhGGZpLnGgxmyfUdkL3PsLKhK8fCr+76/iC77gjyZy+gNpThd9AF2upFNOEn8vOTfJcQ2RhbdcKjOWRtdKwvFfsHkwAPjCqKmFUkc4DXfNZSyKj2+dg7fEZGeLHpdcKLSF6kLv32BsnyRvI0utqe7qOW29Nhf0dkHM+pkT86SPSgIjGSnslkc=
